import postgres from "postgres";
let client:ReturnType<typeof postgres>|null=null;
function sql(){if(!process.env.DATABASE_URL)throw new Error("DATABASE_URL is required");return client??=postgres(process.env.DATABASE_URL,{max:5,prepare:false});}
let initialized=false;
export async function ensureSchema(){if(initialized)return;const db=sql();await db.unsafe(`CREATE TABLE IF NOT EXISTS schools(id BIGSERIAL PRIMARY KEY,name VARCHAR(200) NOT NULL,district VARCHAR(100) NOT NULL,block VARCHAR(100) NOT NULL,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE TABLE IF NOT EXISTS students(id BIGSERIAL PRIMARY KEY,school_id BIGINT NOT NULL REFERENCES schools(id),external_id VARCHAR(64) NOT NULL,class_no SMALLINT NOT NULL,gender VARCHAR(20) NOT NULL DEFAULT '',medium VARCHAR(20) NOT NULL,parent_phone_hash VARCHAR(128) NOT NULL DEFAULT '',created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),UNIQUE(school_id,external_id));
CREATE TABLE IF NOT EXISTS diagnostic_sessions(id BIGSERIAL PRIMARY KEY,student_id BIGINT NOT NULL REFERENCES students(id),started_at TIMESTAMPTZ NOT NULL,completed_at TIMESTAMPTZ,language VARCHAR(5) NOT NULL,device_type VARCHAR(32) NOT NULL,sync_status VARCHAR(16) NOT NULL DEFAULT 'pending');
CREATE TABLE IF NOT EXISTS diagnostic_responses(id BIGSERIAL PRIMARY KEY,session_id BIGINT NOT NULL REFERENCES diagnostic_sessions(id),question_id VARCHAR(64) NOT NULL,selected_option VARCHAR(64) NOT NULL,response_time_ms INTEGER,skipped BOOLEAN NOT NULL DEFAULT FALSE,synced_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),UNIQUE(session_id,question_id));
CREATE TABLE IF NOT EXISTS likert_sessions(id BIGSERIAL PRIMARY KEY,student_id BIGINT NOT NULL REFERENCES students(id),started_at TIMESTAMPTZ NOT NULL,completed_at TIMESTAMPTZ,language VARCHAR(5) NOT NULL,sync_status VARCHAR(16) NOT NULL DEFAULT 'pending');
CREATE TABLE IF NOT EXISTS likert_responses(id BIGSERIAL PRIMARY KEY,session_id BIGINT NOT NULL REFERENCES likert_sessions(id),item_id VARCHAR(64) NOT NULL,score SMALLINT NOT NULL,skipped BOOLEAN NOT NULL DEFAULT FALSE,synced_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),UNIQUE(session_id,item_id));
CREATE TABLE IF NOT EXISTS audit_logs(id BIGSERIAL PRIMARY KEY,actor_type VARCHAR(20) NOT NULL,actor_id VARCHAR(64) NOT NULL DEFAULT '',action VARCHAR(100) NOT NULL,entity_type VARCHAR(100) NOT NULL,entity_id VARCHAR(64) NOT NULL,timestamp TIMESTAMPTZ NOT NULL DEFAULT NOW());`);initialized=true;}