from django.db import migrations,models
import django.db.models.deletion
class Migration(migrations.Migration):
 dependencies=[("gyaan","0001_initial")]
 operations=[
  migrations.CreateModel(name="ConsentRecord",fields=[("id",models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name="ID")),("consent_type",models.CharField(max_length=40)),("consent_text_version",models.CharField(max_length=40)),("consented_at",models.DateTimeField()),("verification_method",models.CharField(max_length=40)),("withdrawn_at",models.DateTimeField(blank=True,null=True)),("student",models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,to="gyaan.student"))]),
  migrations.CreateModel(name="LikertSession",fields=[("id",models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name="ID")),("started_at",models.DateTimeField()),("completed_at",models.DateTimeField(blank=True,null=True)),("language",models.CharField(max_length=5)),("sync_status",models.CharField(default="pending",max_length=16)),("student",models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,to="gyaan.student"))]),
  migrations.CreateModel(name="LikertResponse",fields=[("id",models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name="ID")),("item_id",models.CharField(max_length=64)),("score",models.PositiveSmallIntegerField()),("skipped",models.BooleanField(default=False)),("synced_at",models.DateTimeField(auto_now_add=True)),("session",models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,to="gyaan.likertsession"))]),
  migrations.CreateModel(name="LearningPreference",fields=[("id",models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name="ID")),("visual_score",models.FloatField()),("auditory_score",models.FloatField()),("reading_writing_score",models.FloatField()),("kinesthetic_score",models.FloatField()),("top_preference",models.CharField(max_length=30)),("second_preference",models.CharField(max_length=30)),("is_mixed",models.BooleanField(default=False)),("computed_at",models.DateTimeField(auto_now_add=True)),("student",models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,to="gyaan.student"))]),
  migrations.CreateModel(name="GapReport",fields=[("id",models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name="ID")),("weak_topics",models.JSONField(default=list)),("strong_topics",models.JSONField(default=list)),("suggested_next_step",models.TextField()),("generated_at",models.DateTimeField(auto_now_add=True)),("pdf_url",models.URLField(blank=True)),("session",models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,to="gyaan.diagnosticsession")),("student",models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,to="gyaan.student"))]),
  migrations.CreateModel(name="RecheckSession",fields=[("id",models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name="ID")),("started_at",models.DateTimeField()),("completed_at",models.DateTimeField(blank=True,null=True)),("improvement_json",models.JSONField(default=dict)),("sync_status",models.CharField(default="pending",max_length=16)),("original_session",models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,to="gyaan.diagnosticsession")),("student",models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,to="gyaan.student"))]),
  migrations.CreateModel(name="GuidanceCard",fields=[("id",models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name="ID")),("aspiration",models.CharField(blank=True,max_length=300)),("obstacle",models.CharField(blank=True,max_length=500)),("next_step_options",models.JSONField(default=list)),("reviewed_by_teacher",models.BooleanField(default=False)),("generated_at",models.DateTimeField(auto_now_add=True)),("student",models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,to="gyaan.student"))]),
  migrations.AddConstraint(model_name="likertresponse",constraint=models.UniqueConstraint(fields=("session","item_id"),name="uniq_likert_response"))
 ]