//! Constrained generation boundary. Models receive a response specification and are
//! verified after generation; they are never the safety authority.
use crate::types::MoveId;
#[derive(Debug,Clone)]pub struct ResponseSpec{pub move_id:MoveId,pub goal:String,pub tone:String,pub max_chars:usize,pub required:Vec<String>,pub forbidden:Vec<String>}
pub trait Generator:Send+Sync{fn generate(&self,spec:&ResponseSpec,context:&str)->String;}
pub struct TemplateGenerator;
impl Generator for TemplateGenerator{fn generate(&self,spec:&ResponseSpec,context:&str)->String{let prefix=match spec.move_id{MoveId::M01OpenReflection=>"It sounds like something important is sitting with you.",MoveId::M02Validation=>"That sounds difficult, and it makes sense to take a moment with it.",MoveId::M03ExploratoryQuestion=>"What part of this feels most important right now?",MoveId::M04Grounding=>"Let’s slow things down and notice what is happening right now.",MoveId::M07HumanConnection=>"Would reaching out to someone you trust feel possible right now?",_=>"We can take this one step at a time."};let mut out=prefix.to_string();if !context.trim().is_empty()&&matches!(spec.move_id,MoveId::M01OpenReflection|MoveId::M03ExploratoryQuestion){out.push_str(" ");out.push_str(context.trim());}out.chars().take(spec.max_chars).collect()}}
#[derive(Debug,Clone,PartialEq,Eq)]pub enum Verification{Pass,Reject(String)}
pub fn verify(spec:&ResponseSpec,text:&str)->Verification{if text.trim().is_empty(){return Verification::Reject("empty response".into());}if text.chars().count()>spec.max_chars{return Verification::Reject("length limit exceeded".into());}let lower=text.to_lowercase();for f in &spec.forbidden{if lower.contains(&f.to_lowercase()){return Verification::Reject(format!("forbidden content: {f}"));}}for r in &spec.required{if !lower.contains(&r.to_lowercase()){return Verification::Reject(format!("missing required content: {r}"));}}Verification::Pass}
#[cfg(test)]mod tests{use super::*;#[test]fn verifier_blocks_forbidden(){let s=ResponseSpec{move_id:MoveId::M02Validation,goal:"support".into(),tone:"warm".into(),max_chars:100,required:vec![],forbidden:vec!["diagnose".into()]};assert!(matches!(verify(&s,"I can diagnose you"),Verification::Reject(_)));}}
