"use client";
import {useEffect,useState} from "react";
import {type ConfirmationResult} from "firebase/auth";
import {subscribeAuth,currentIdToken,requestOtp,signOutUser} from "../lib/firebase-client";
import {enqueue,getDiagnosticSession,saveDiagnosticSession,db} from "../lib/offline";
type Student={id:number;external_id:string;class_no:number;medium:string}; type Q={id:string;prompt:string;options:string[]};
async function api(path:string,token:string,init:RequestInit={}){return fetch(path,{...init,headers:{...(init.headers||{}),Authorization:"Bearer "+token,"content-type":"application/json"}});}
export default function Home(){const[user,setUser]=useState<any>(null),[phone,setPhone]=useState(""),[otp,setOtp]=useState(""),[confirm,setConfirm]=useState<ConfirmationResult|null>(null),[students,setStudents]=useState<Student[]>([]),[studentId,setStudentId]=useState(0),[classNo,setClassNo]=useState<8|9>(8),[subject,setSubject]=useState<"maths"|"science">("maths"),[session,setSession]=useState<any>(null),[qs,setQs]=useState<Q[]>([]),[i,setI]=useState(0),[answers,setAnswers]=useState<Record<string,string>>({}),[likert,setLikert]=useState<any[]>([]),[li,setLi]=useState(0),[error,setError]=useState("");
useEffect(()=>subscribeAuth(setUser),[]);
useEffect(()=>{if(user)void (async()=>{const t=await user.getIdToken();const r=await api("/api/v1/students",t);if(r.ok)setStudents((await r.json()).students);})();},[user]);
const start=async()=>{const t=await user.getIdToken(true);const r=await api("/api/v1/sessions",t,{method:"POST",body:JSON.stringify({student_id:studentId,class:classNo,subject,language:"or"})});const j=await r.json();if(!r.ok){setError(j.error||"session_failed");return;}await saveDiagnosticSession({sessionId:j.session_id,clientSessionId:j.client_session_id,sessionToken:j.session_token,expiresAt:j.expires_at});setSession(j);setQs(j.questions);setI(0);setAnswers({});};
const choose=async(o:string)=>{const q=qs[i];setAnswers(a=>({...a,[q.id]:o}));await enqueue({entity:"diagnostic_response",action:"create",payload:{question_id:q.id,selected_option:o,response_time_ms:1000}});};
const flush=async()=>{const s=await getDiagnosticSession(),t=await currentIdToken();if(!s||!t)return;const items=(await db.queue.where("status").anyOf("pending","failed").sortBy("createdAt")).slice(0,20);if(!items.length)return;const r=await api("/api/v1/sync/batch",t,{method:"POST",body:JSON.stringify({session_id:s.sessionId,session_token:s.sessionToken,items})});if(r.ok){const j=await r.json();await db.queue.bulkDelete(items.filter(x=>(j.idempotency_ids||[]).includes(x.id)).map(x=>x.id));}};
const finish=async()=>{await flush();const t=await currentIdToken();if(!t){setError("auth_required");return;}const r=await api("/api/v1/likert/sessions",t,{method:"POST",body:JSON.stringify({student_id:studentId,diagnostic_session_id:session.session_id})});if(r.ok){const j=await r.json();setLikert(j.items||[]);(session as any).likert_session_id=j.likert_session_id;}};
const chooseLikert=async(score:number)=>{const item=likert[li];await enqueue({entity:"likert_response",action:"create",payload:{likert_session_id:session.likert_session_id,item_id:item.id,score}});if(li+1<likert.length)setLi(li+1);else{await flush();setSession(null);setLikert([]);}};
if(!user)return <main className="shell"><section className="card"><h1>Gyaan Saathi</h1><p>Teacher sign-in</p><input value={phone} onChange={e=>setPhone(e.target.value)} placeholder="+91..." /><button className="primary" onClick={async()=>{try{setConfirm(await requestOtp(phone,"recaptcha"))}catch{setError("otp_unavailable")}}}>Send OTP</button><div id="recaptcha"/>{confirm&&<><input value={otp} onChange={e=>setOtp(e.target.value)} placeholder="OTP"/><button className="primary" onClick={()=>confirm.confirm(otp).catch(()=>setError("invalid_otp"))}>Verify</button></>}{error&&<p>{error}</p>}</section></main>;
if(session)return <main className="shell"><section className="card">{likert.length?<><p>Learning check {li+1} of {likert.length}</p><h2>{likert[li].text}</h2><div className="options">{[1,2,3,4,5].map(n=><button className="option" key={n} onClick={()=>void chooseLikert(n)}>{n}</button>)}</div></>:<><p>Question {i+1} of {qs.length}</p><h2>{qs[i]?.prompt}</h2><div className="options">{qs[i]?.options.map(o=><button className={"option "+(answers[qs[i].id]===o?"selected":"")} key={o} onClick={()=>void choose(o)}>{o}</button>)}</div><button className="primary" disabled={!answers[qs[i]?.id]} onClick={()=>i+1<qs.length?setI(i+1):void finish()}>{i+1<qs.length?"Next":"Finish"}</button></>}</section></main>;
return <main className="shell"><header className="topbar"><b>Gyaan Saathi</b><button onClick={()=>void signOutUser()}>Sign out</button></header><section className="card"><h1>Start diagnostic</h1><select value={studentId} onChange={e=>setStudentId(Number(e.target.value))}><option value={0}>Select student</option>{students.map(s=><option key={s.id} value={s.id}>{s.external_id} · Class {s.class_no}</option>)}</select><select value={classNo} onChange={e=>setClassNo(Number(e.target.value) as 8|9)}><option value={8}>Class 8</option><option value={9}>Class 9</option></select><select value={subject} onChange={e=>setSubject(e.target.value as any)}><option value="maths">Maths</option><option value="science">Science</option></select><button className="primary" disabled={!studentId} onClick={()=>void start()}>Start 15-minute diagnostic</button>{error&&<p>{error}</p>}</section></main>;}